[package]
name = "jotx"
version = "0.1.0"
edition = "2024"

[dependencies]
copypasta = "0.10"
x-win = "5.3.2"
once_cell = "1.19"
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
pid = "4.0"
